= Dateibeschreibung

Bei der Bewirtschaftung eines Themas gibt es Attribute, deren Werte nicht frei vergeben, sondern aus einer vorgegebenen Liste selektiert werden müssen. Dies gilt z.B. für den Gemeindenamen, welcher aus einer Liste der Schwyzer Gemeinden auszuwählen ist. Bei den vorgegebenen Werten spricht man von Stammdaten. Sie werden in einer eigenen Datei gehalten (`+Stammdaten.xtf+`) und dienen als Grundlage für die Datenerfassung.

Änderungen am Datenmodell und/oder Änderungen an den Werten der Stammdaten führen zu Anpassungen in der Datei `+Stammdaten.xtf+`. Die nachfolgende Tabelle zeigt, zu welchem Zeitpunkt welche Stammdaten für welches Datenmodell zu verwenden ist.

[cols="20%, 20%, 20%, 40%",options="header"]
|===
| Modell +
(Version) | Stammdaten- +
kennung | gültig ab | Beschreibung
| SZ_Oekomorphologie_Fliessgewaesser_V1_1 +
(2024-07-24)
| https://raw.githubusercontent.com/ch-sz-geo/A026/Bearbeitung/data/Stammdaten.xtf[*2000-01-01*]
| 2000-01-01
| Diese Datei enthält die aktuell gültigen Stammdaten für die Datenerfassung.
|===
