== Modelltransformationen
=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: https://models.geo.admin.ch/BAFU/Revitalisierung_Fliessgewaesser_V1_2.ili[Revitalisierung_Fliessgewaesser_V1_2 (Version: 2024-06-13)]

==== Klasse `+AbschOekomorph+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| Liniengeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+LinearpositionVon+` und `+LinearpositionBis+`
| `+Abschnitt+`
| `+Sohlenbreite+`
| `+Sohlenbreite+`
| - - -
| `+Eindolung+`
| Wert von `+Breitenvariabilitaet.OID+` +
hergeleitet über `+Breitenvariabilitaet__AbschOekomorph.rBreitenvariabilitaet+`
| `+Breitenvariabilitaet+`
| Wert von `+Tiefenvariabilitaet.OID+` +
hergeleitet über `+Tiefenvariabilitaet__AbschOekomorph.rTiefenvariabilitaet+`
| `+Tiefenvariabilitaet+`
| Wert von `+Sohlenverbauung.OID+` +
hergeleitet über `+Sohlenverbauung__AbschOekomorph.rSohlenverbauung+`
| `+Sohlenverbauung+`
| Wert von `+Sohlmaterial.OID+` +
hergeleitet über `+Sohlmaterial__AbschOekomorph.rSohlmaterial+`
| `+Sohlmaterial+`
| Wert von `+Boeschungsfussverbau.OID+` +
hergeleitet über `+BoeschungsfussverbauLinks__AbschOekomorph.rBoeschungsfussverbauLinks+`
| `+BoeschVB_l+`
| Wert von `+Boeschungsfussverbau.OID+` +
hergeleitet über `+BoeschungsfussverbauRechts__AbschOekomorph.rBoeschungsfussverbauRechts+`
| `+BoeschVB_r+`
| Wert von `+Boeschungsmaterial.OID+` +
hergeleitet über `+BoeschungsmaterialLinks__AbschOekomorph.rBoeschungsmaterialLinks+`
| `+Material_l+`
| Wert von `+Boeschungsmaterial.OID+` +
hergeleitet über `+BoeschungsmaterialRechts__AbschOekomorph.rBoeschungsmaterialRechts+`
| `+Material_r+`
| `+UferbreiteLinks+`
| `+Uferbrei_l+`
| `+UferbreiteRechts+`
| `+Uferbrei_r+`
| Wert von `+Uferbeschaffenheit.OID+` +
hergeleitet über `+UferbeschaffenheitLinks__AbschOekomorph.rUferbeschaffenheitLinks+`
| `+Uferbesc_l+`
| Wert von `+Uferbeschaffenheit.OID+` +
hergeleitet über `+UferbeschaffenheitRechts__AbschOekomorph.rUferbeschaffenheitRechts+`
| `+Uferbesc_r+`
| Wert von `+Bewuchs.OID+` +
hergeleitet über `+Algenbewuchs__AbschOekomorph.rAlgenbewuchs+`
| `+Algenbewuchs+`
| Wert von `+Bewuchs.OID+` +
hergeleitet über `+Makrophytenbewuchs__AbschOekomorph.rMakrophytenbewuchs+`
| `+Makrophytenbewuchs+`
| Wert von `+Totholz.OID+` +
hergeleitet über `+Totholz__AbschOekomorph.rTotholz+`
| `+Totholz+`
| Wert von `+Klasse.OID+` +
hergeleitet über `+Klasse__AbschOekomorph.rKlasse+`
| `+Klasse+`
| `+Bemerkung+`
| `+Notizen+`
|===

==== Klasse `+Absturz+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| Punktgeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` und `+Linearposition+` | `+Ort+`
| `+Kennung+` | `+Nummer+`
| Wert von `+Absturztyp.OID+` +
hergeleitet über `+Absturztyp__Absturz.rAbsturztyp+` | `+Typ+`
| Wert von `+Absturzmaterial.OID+` +
hergeleitet über `+Absturzmaterial__Absturz.rAbsturzmaterial+` | `+Material+`
| `+Hoehe+` | `+Hoehe+`
| `+Bemerkung+` | `+Notizen+`
|===

==== Klasse `+Bauwerk+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| Punktgeometrie, gebildet über die lineare Referenzierung auf der Grundlage von `+Achsgeometrie+` sowie `+Linearposition+` und `+Querabstand+` | `+Ort+`
| `+Kennung+` | `+Identifikator+`
a| Wert von `+Bauwerktyp.OID+` +
hergeleitet über `+Bauwerktyp__Bauwerk.rBauwerktyp+` +
Regel +
Die Werte von

- `+andere_nicht_kartierter_Zufluss+`,
- `+andere_Einleitung+`,
- `+andere_Ablagerung+` und
- `+andere+`

sind dem Bundestyp `+Bauwerktyp1+` ("nicht bestimmt") zuzuordnen.
| `+Typ+`
| `+Hoehe+` | `+Hoehe+`
| `+Bemerkung+` | `+Notizen+`
|===

==== Klasse `+AbschOEB+`
Die Daten zu dieser Klasse werden im Thema A180 geführt. Die Transformationsregeln finden sich https://ch-sz-geo.github.io/A180/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+AbschNutzen+`
Die Daten zu dieser Klasse werden im Thema A180 geführt. Die Transformationsregeln finden sich https://ch-sz-geo.github.io/A180/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+AbschPrio+`
Die Daten zu dieser Klasse werden im Thema A180 geführt. Die Transformationsregeln finden sich https://ch-sz-geo.github.io/A180/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].

==== Klasse `+AbsturzNutzen+`
Die Daten zu dieser Klasse werden im Thema A180 geführt. Die Transformationsregeln finden sich https://ch-sz-geo.github.io/A180/docs/modelldokumentation.html#_transformation_ins_minimale_geodatenmodell_des_bundes[hier].


ifdef::backend-pdf[]
<<<
endif::[]
